name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: zulu@1.11
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 -Dtest.prop.minSuccessful=1000000 -Dtest.prop.sizeRange=100 test
    - name: Benchmark
      run: sbt "benchmark/jmh:run -i10 -f1 -t1"
